[project]
name = "landingsmanager"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "flask-cors>=6.0.1",
    "flask-mail>=0.10.0",
    "requests>=2.32.4",
]
